---
params:
  data: data
  set_title: set_title
  mixedData: mixedData
  ContVar: ContVar
  CatVar: CatVar
title: "`r params$set_title`"
always_allow_html: true
---

```{r options, include=FALSE}
if(!require(rmarkdown)){
  install.packages("rmarkdown") #Export tables
  library(rmarkdown)
}

if(!require(knitr)){
  install.packages("knitr") # Tables Format
  library(knitr)
}

if(!require(ggplot2)){
  install.packages("ggplot2") # Graph creation
  library(ggplot2)
}

if(!require(hopkins)){
  install.packages("hopkins") # Hopkins Statistic
  library(hopkins)
}

if(!require(mclust)){
  install.packages("mclust") # Model-Based clustering
  library(mclust)
}

if(!require(stats)){
  install.packages("stats") # K-means and Hierarchical clustering
  library(stats)
}

if(!require(kamila)){ 
  install.packages("kamila") # KAMILA clustering
  library(kamila)
}

if(!require(clustMixType)){
  install.packages("clustMixType") # K-prototypes clustering
  library(clustMixType)
}

if(!require(clusterSim)){
  install.packages("clusterSim") # Calinski-Harabasz index
  library(clusterSim)
}

if(!require(fpc)){
  install.packages("fpc") # Davies-Bouldin index
  library(fpc)
}

if(!require(dplyr)){
  install.packages("dplyr") # Functionality
  library(dplyr)
}

if(!require(factoextra)){
  install.packages("factoextra") # Principal Component Analysis
  library(factoextra)
}

if(!require(PCAmixdata)){
  install.packages("PCAmixdata") # PCA for Mixed Data
  library(PCAmixdata)
}

data <- params$data
ContVar <- params$ContVar
CatVar <- params$CatVar
mixedData <- params$mixedData
```


## Data information

```{r na, fig.show="hold", out.width="50%", echo = FALSE}
barplot(prop.table(table(is.na(data))), width = 0.4)
```


```{r data_info, echo=FALSE}
data <- na.omit(data)

knitr::kable(head(data))

continuous_data <- data[, ContVar]

categorical_data <- data[, CatVar]

data_standardized <- as.data.frame(scale(continuous_data))

data_blind <- data[, c(-14, -15)]

patients_mahalanobis <- round(data.frame(Mahalanobis = mahalanobis(continuous_data, colMeans(continuous_data), cov(continuous_data))), 4)
patients_mahalanobis$pvalue <- round(pchisq(patients_mahalanobis$Mahalanobis, df=3, lower.tail=FALSE), 6)

Outliers <- patients_mahalanobis[patients_mahalanobis$pvalue < 0.001, ]
```


## Outlier Detection

```{r Outliers, echo=FALSE}
if (nrow(Outliers) > 0 ) {
  knitr::kable(Outliers)
} else {
  print("No outliers detected")
}

```


## Hopkins Statistic

```{r datainfo_hopkins, echo=FALSE}
set.seed("1")
datainfo <- data.frame("Samples" = nrow(data_standardized),
                       "Variables" = ncol(data_standardized),
                       "Hopkins" = round(hopkins(data_standardized), 4),
                       "Outliers" = nrow(Outliers))

knitr::kable(datainfo)
```

```{r HC, include=FALSE}
### HIERARCHICAL CLUSTERING MODEL

hc_list <- list()
hc_G_values <- 2:10

d <- dist(as.matrix(continuous_data))

set.seed("1")
h <- hclust(d, method = "ward.D2", members = NULL)

# Silhouette score
silhouette_score_hc <- function(G){
  set.seed("1")
  h <- hclust(d, method = "ward.D2", members = NULL)
  cut <- cutree(h, k = G)
  ss <- silhouette(cut, dist(continuous_data))
  mean(ss[, 3])
}

avg_sil_hc <- sapply(hc_G_values, silhouette_score_hc)
Max_silhouette_hc <- max(avg_sil_hc)

cut <- cutree(h, k = (which.max(avg_sil_hc)+1))

plot(h, labels = NULL, hang = 0.1, check = TRUE,
     axes = TRUE, frame.plot = FALSE, ann = TRUE,
     main = "Cluster Dendrogram",
     sub = NULL, xlab = "Samples")
rect.hclust(h , k = which.max(avg_sil_hc)+1, border = 2:8)

continuous_data_hc <- mutate(continuous_data, cluster = cut)


# Davies-Bouldin's Index
DB_HC <- index.DB(continuous_data, cut, d=NULL, centrotypes="centroids", p=2, q=2)

# Calinski-Harabasz index
CH_HC <- calinhara(continuous_data, cut)

data$HCCluster <- as.factor(cut)
```

```{r MBC, include=FALSE}
### MODEL-BASED CLUSTERING MODEL

MBC_list <- list()
MClust_G_values <- 2:10

for (G in MClust_G_values) {
  set.seed("1")
  MBC <- Mclust(data_standardized, G)
  MBC_list[[as.character(G)]] <- MBC
}

# Silhouette score
silhouette_score_MBC <- function(G){
  set.seed("1")
  MBC <- Mclust(data_standardized, G)
  ss <- silhouette(MBC$classification, dist(data_standardized))
  mean(ss[, 3])
}

avg_sil_MBC <- sapply(MClust_G_values, silhouette_score_MBC)
plot(MClust_G_values, type='b', avg_sil_MBC, xlab='Number of clusters', 
     ylab='Average Silhouette Scores', 
     frame=FALSE, main="Silhouette Score (MBC)")
Max_silhouette_MBC <- max(avg_sil_MBC)

# BIC
for (G in MClust_G_values) {
  set.seed("1")
  BIC_MBC <- lapply(MBC_list, BIC)
}


# Davies-Bouldin's Index
DB_MBC <- index.DB(data_standardized, MBC_list[[as.character(which.max(avg_sil_MBC)+1)]]$classification, 
                   d=NULL, centrotypes="centroids", p=2, q=2)


# Calinski-Harabasz index
CH_MBC <- calinhara(data_standardized, MBC_list[[as.character(which.max(avg_sil_MBC)+1)]]$classification)

# Cluster visualization
plot(MBC_list[[as.character(which.max(avg_sil_MBC)+1)]], what="classification")
summary(MBC_list[[as.character(which.max(avg_sil_MBC)+1)]])

data$MBCcluster <- as.factor(MBC_list[[as.character(which.max(avg_sil_MBC)+1)]]$classification)
```


```{r kmeans, include = FALSE}
### K-MEANS CLUSTERING MODEL

kmeans_list <- list()
kmeans_G_values <- 2:10

for (G in kmeans_G_values) {
  set.seed("1")
  k <-kmeans(continuous_data, G)
  kmeans_list[[as.character(G)]] <- k
}

# Silhouette score
silhouette_score_kmeans <- function(kmeans_G_values){
  set.seed("1")
  k <-kmeans(continuous_data, kmeans_G_values, nstart = 50)
  ss <- silhouette(k$cluster, dist(continuous_data))
  mean(ss[, 3])
}

avg_sil_kmeans <- sapply(kmeans_G_values, silhouette_score_kmeans)
Max_silhouette_kMeans <- max(avg_sil_kmeans)

# BIC
kmeansBIC <- function(fit){
  m = ncol(fit$centers) 
  n = length(fit$cluster)
  k = nrow(fit$centers)
  D = fit$tot.withinss
  return(D + log(n) * m * k)
}

bic_k <- sapply(kmeans_G_values, FUN = 
                  function(k) 
                    kmeansBIC(kmeans(continuous_data, centers = k, nstart = 20, iter.max = 25)))

# Davies-Bouldin's Index
DB_Kmeans <- index.DB(continuous_data, kmeans_list[[as.character(which.max(avg_sil_kmeans)+1)]]$cluster, d=NULL, 
                      centrotypes="centroids", p=2, q=2)

# Calinski-Harabasz index
CH_Kmeans <- calinhara(continuous_data, kmeans_list[[as.character(which.max(avg_sil_kmeans)+1)]]$cluster)

data$Kmeanscluster <- as.factor(kmeans_list[[as.character(which.max(avg_sil_kmeans)+1)]]$cluster)
```

```{r kamila, include = FALSE}
### KAMILA CLUSTERING MODEL

kamila_list <- list()
numClust_values <- 2:10

for (numClust in numClust_values) {
  set.seed("1")
  kamila <- kamila(conVar = data_standardized, 
                             catFactor = categorical_data,
                             numClust = numClust,
                             numInit = 100)
  kamila_list[[as.character(numClust)]] <- kamila
}


# Silhouette score
silhouette_score_kamila <- function(K){
  set.seed("1")
  kamila <- kamila(conVar = data_standardized, 
                   catFactor = categorical_data,
                   numClust = K,
                   numInit = 100)
  ss <- silhouette(kamila$finalMemb, dist(data_standardized))
  mean(ss[, 3])
}

avg_sil_kamila <- sapply(numClust_values, silhouette_score_kamila)
Max_silhouette_kamila <- max(avg_sil_kamila)

# Davies-Bouldin's Index
DB_Kamila <- index.DB(data_standardized, kamila_list[[as.character(which.max(avg_sil_kamila)+1)]]$finalMemb, d=NULL, 
                      centrotypes="centroids", p=2, q=2)

# Calinski-Harabasz index
CH_Kamila <- calinhara(data_standardized, kamila_list[[as.character(which.max(avg_sil_kamila)+1)]]$finalMemb)


data$kamilacluster <- as.factor(kamila_list[[as.character(which.max(avg_sil_kamila)+1)]]$finalMemb)

# PCA for MIXED DATA
split <- splitmix(data_blind)
pcamix <- PCAmix(X.quanti=split$X.quanti,
                 X.quali=split$X.quali,
                 rename.level=TRUE, 
                 graph=TRUE, ndim=2)



# PS plot
kamila_ps <- NULL
numClust_values <- 2:10

suppressWarnings(
  for (numClust in numClust_values) {
  set.seed("1")
  kamila <- kamila(conVar = data_standardized, 
                   catFactor = categorical_data,
                   numClust = numClust,
                   calcNumClust = "ps",
                   numInit = 100)
  kamila <- kamila$nClust$psValues
  kamila_ps <- append(kamila_ps, kamila)
})

kamila_ps_df <- data.frame("Clusters" = c((1:length(kamila_ps))+1),
                           "ps" = kamila_ps)
```

```{r kproto, include = FALSE}
### K-PROTOTYPES CLUSTERING MODEL

kproto_list <- list()
Kp <- 2:10

for (protoclust in Kp) {
  set.seed("1")
  kproto <- kproto(data_blind, protoclust, nstart = 5)
  kproto_list[[as.character(protoclust)]] <- kproto
}

# Silhouette score
silhouette_score_kproto <- function(Kp){
  set.seed("1")
  kproto <- kproto(data_blind, Kp, nstart = 5)
  ss <- silhouette(kproto$cluster, dist(data_blind))
  mean(ss[, 3])
}

avg_sil_kproto <- sapply(Kp, silhouette_score_kproto)
Max_silhouette_kproto <- max(avg_sil_kproto)

# Davies-Bouldin's Index
DB_Kproto <- index.DB(continuous_data, kproto_list[[as.character(which.max(avg_sil_kproto)+1)]]$cluster, d=NULL, 
                      centrotypes="centroids", p=2, q=2)

# Calinski-Harabasz index
CH_Kproto <- calinhara(continuous_data, kproto_list[[as.character(which.max(avg_sil_kproto)+1)]]$cluster)


fit_df <- factor(kproto_list[[as.character(which.max(avg_sil_kproto)+1)]]$cluster, order =  TRUE,
                 levels = c(1:2))
fit <- data.frame(data_standardized, fit_df)
result_df <- kproto_list[[as.character(which.max(avg_sil_kproto)+1)]]$centers
Member <- kproto_list[[as.character(which.max(avg_sil_kproto)+1)]]$size
result <- data.frame(Member, result_df)
result


data$kprotocluster <- as.factor(kproto_list[[as.character(which.max(avg_sil_kproto)+1)]]$cluster)

```


## Silhouette Scores

```{r silhouette, fig.show="hold", out.width="50%", echo = FALSE}
par(mar = c(4, 4, 4, 4) + 0.1)

plot(hc_G_values, type='b', avg_sil_hc, xlab='Number of clusters', 
     ylab='Average Silhouette Scores', frame=FALSE, 
     main="Silhouette Score (Hierarchical Clustering)")

plot(MClust_G_values, type='b', avg_sil_MBC, xlab='Number of clusters', 
     ylab='Average Silhouette Scores', 
     frame=FALSE, main="Silhouette Score (MBC)")

plot(kmeans_G_values, type='b', avg_sil_kmeans, xlab='Number of clusters', 
     ylab='Average Silhouette Scores', frame=FALSE, main="Silhouette Score (K-means)")

plot(numClust_values, type='b', avg_sil_kamila, xlab='Number of clusters', 
     ylab='Average Silhouette Scores', frame=FALSE, main="Silhouette Score (Kamila)")

plot(Kp, type='b', avg_sil_kproto, xlab='Number of clusters', 
     ylab='Average Silhouette Scores', frame=FALSE, main="Silhouette Score (k-Prototypes)")
```


## Clustering Models

```{r Cluster_final, echo=FALSE}
Cluster_comparisons_Final <- data.frame(
              "Model" = c("Hierarchical Clustering", "MBC", "K-means", "Kamila", "K-Prototypes"),
              "Nº of clusters" = c(which.max(avg_sil_hc)+1, which.max(avg_sil_MBC)+1, which.max(avg_sil_kmeans)+1, which.max(avg_sil_kamila)+1, which.max(avg_sil_kproto)+1),
              "Silhouette coefficient" = c(round(Max_silhouette_hc, 3), round(Max_silhouette_MBC, 3), round(Max_silhouette_kMeans, 3), round(Max_silhouette_kamila, 3), round(Max_silhouette_kproto, 3)),
              "Davies-Bouldin index" = c(round(DB_HC$DB, 3), round(DB_MBC$DB, 3), round(DB_Kmeans$DB, 3), round(DB_Kamila$DB, 3), round(DB_Kproto$DB, 3)),
              "Calinski-Harabasz" = c(round(CH_HC, 3), round(CH_MBC, 3), round(CH_Kmeans, 3), round(CH_Kamila, 3), round(CH_Kproto, 3)))

knitr::kable(Cluster_comparisons_Final)
```

### Hierarchical Clustering

```{r HC_plots, echo=FALSE}

plot(h, labels = NULL, hang = 0.1, check = TRUE,
     axes = TRUE, frame.plot = FALSE, ann = TRUE,
     main = "Cluster Dendrogram",
     sub = NULL, xlab = "Samples")
rect.hclust(h , k = which.max(avg_sil_hc)+1, border = 2:8)

```

### Model-Based Clustering

```{r MBC_plots, echo=FALSE}
plot(MClust_G_values, BIC_MBC, xlab = 'Clusters', ylab = 'BIC from MBC')

# Cluster visualization
fviz_cluster(MBC_list[[as.character(which.max(avg_sil_MBC)+1)]], data = data_standardized,
             palette = c("#2E9FDF", "#38BB72", "#5C2FAF", "#BB70CA", "#5575CA", 
                         "#BB7063", "#25A8C2", "#9270CA", "#BB702A", "#A32332"), 
             geom = c("point", "text"),
             pointsize = 1.5,
             ellipse.type = "convex",
             main = "Cluster Plot (MBC)",
             ggtheme = theme_bw()
)

```

### K-means Clustering

```{r kmeans_plots, echo = FALSE}
plot(kmeans_G_values, bic_k, xlab = 'Clusters', ylab = 'BIC from kmeans')


# Cluster visualization
fviz_cluster(kmeans_list[[as.character(which.max(avg_sil_kmeans)+1)]], data = continuous_data,
             palette = c("#2E9FDF", "#38BB72", "#5C2FAF", "#BB70CA", "#5575CA", 
                         "#BB7063", "#25A8C2", "#9270CA", "#BB702A", "#A32332"), 
             geom = c("point", "text"),
             pointsize = 1.5,
             ellipse.type = "convex",
             main = "Cluster Plot (K-means)",
             ggtheme = theme_bw()
)

```

### Kamila Clustering

```{r kamila_plot, echo = FALSE}
plot(kamila_ps_df$Clusters, kamila_ps_df$ps, type='b', ylab = "Prediction Strength", 
     xlab = "Number of Clusters", frame=FALSE, main="Prediction Strength Values (Kamila)")

plot(pcamix, coloring.ind=data$kamilacluster)
```

### K-prototypes Clustering

```{r kproto_plots, echo = FALSE}
plot(pcamix, coloring.ind=data$kprotocluster)
```



## Model Comparisons

```{r ARI, include = FALSE}
ARIDF <- data.frame ("Comparisons" = c("HC vs MBC", "HC vs K-means", "HC vs Kamila", "HC vs K-prototypes", 
                                       "MBC vs K-means", "MBC vs Kamila", "MBC vs K-prototypes",
                                       "K-means vs Kamila", "K-means vs K-prototypes",
                                       "Kamila vs K-prototypes"),
                     "ARI" = round(c(adjustedRandIndex(data$HCCluster, 
                                                       data$MBCcluster), 
                               adjustedRandIndex(data$HCCluster, 
                                                 data$Kmeanscluster),
                               adjustedRandIndex(data$HCCluster, 
                                                 data$kamilacluster),
                               adjustedRandIndex(data$HCCluster, 
                                                 data$kprotocluster),
                               adjustedRandIndex(data$MBCcluster, 
                                                 data$Kmeanscluster),
                               adjustedRandIndex(data$MBCcluster, 
                                                 data$kamilacluster),
                               adjustedRandIndex(data$MBCcluster, 
                                                 data$kprotocluster),
                               adjustedRandIndex(data$Kmeanscluster, 
                                                 data$kamilacluster),
                               adjustedRandIndex(data$Kmeanscluster, 
                                                 data$kprotocluster),
                               adjustedRandIndex(data$kamilacluster, 
                                                 data$kprotocluster)), 4))

ARIDF <- ARIDF[order(ARIDF$ARI, decreasing = TRUE),]

```

```{r ARI_table, echo = FALSE}
knitr::kable(ARIDF)
```

